version: 2.1
jobs:

  test:
    docker:
      - image: cimg/node:12.22.10

    steps:
      - checkout
      - run: npm ci
      - run: npm run test

workflows:
  version: 2
  test:
    jobs:
      - test