version: 2.1
jobs:

  test:
    docker:
      - image: cimg/node:18.16.1

    steps:
      - run: npm install npm@9.7.2
      - checkout
      - run: npm ci
      - run: npm run test

workflows:
  version: 2
  test:
    jobs:
      - test