version: 2.1
jobs:

  test:
    docker:
      - image: cimg/node:20.11.0

    steps:
      - checkout
      - run: npm install npm@10.3.0
      - run: npm ci
      - run: npm run test

workflows:
  version: 2
  test:
    jobs:
      - test